-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 15:31:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventus` ;

-- -----------------------------------------------------
-- Schema inventus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventus` ;
USE `inventus` ;

-- -----------------------------------------------------
-- Table `inventus`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `inventus`.`usuarios` (
  `idUsuarios` BIGINT NOT NULL,
  `idPessoas` BIGINT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` TEXT NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `fk_usuarios_pessoas` (`idPessoas` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_pessoas`
    FOREIGN KEY (`idPessoas`)
    REFERENCES `inventus`.`pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `inventus`.`pessoas` (
  `idPessoas` BIGINT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idPessoas`),
  UNIQUE INDEX `idPessoas_UNIQUE` (`idPessoas` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_pessoas_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_pessoas_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_pessoas_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_usuarios_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_usuarios_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_usuarios_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`acessos` ;

CREATE TABLE IF NOT EXISTS `inventus`.`acessos` (
  `idAcessos` BIGINT NOT NULL,
  `identificador` CHAR(1) NOT NULL DEFAULT 'A',
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idAcessos`),
  INDEX `fk_acessos_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_acessos_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_acessos_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  CONSTRAINT `fk_acessos_usuarios_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acessos_usuarios_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acessos_usuarios_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`usuarios_has_acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`usuarios_has_acessos` ;

CREATE TABLE IF NOT EXISTS `inventus`.`usuarios_has_acessos` (
  `idUsuarios` BIGINT NOT NULL,
  `idAcessos` BIGINT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `idAcessos`),
  INDEX `fk_hasacessos_acessos` (`idAcessos` ASC) VISIBLE,
  INDEX `fk_hasacessos_usuarios` (`idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_hasacessos_usuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hasacessos_acessos`
    FOREIGN KEY (`idAcessos`)
    REFERENCES `inventus`.`acessos` (`idAcessos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`estoque` ;

CREATE TABLE IF NOT EXISTS `inventus`.`estoque` (
  `idestoque` BIGINT NOT NULL AUTO_INCREMENT,
  `nomeItem` TEXT NOT NULL,
  `descricao` TEXT NULL,
  `quantidade` INT NOT NULL DEFAULT 0,
  `valorUnidade` DECIMAL(10,2) NOT NULL,
  `valorVendaUnidade` DECIMAL(10,2) NOT NULL,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idestoque`),
  INDEX `fk_estoque_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_estoque_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_estoque_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_usuarios_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_usuarios_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_usuarios_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`rotas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`rotas` ;

CREATE TABLE IF NOT EXISTS `inventus`.`rotas` (
  `idrotas` BIGINT NOT NULL AUTO_INCREMENT,
  `rota` TEXT NOT NULL,
  `method` VARCHAR(20) NOT NULL,
  `params` TEXT NULL,
  `body` TEXT NULL,
  `query` TEXT NULL,
  `negado` TINYINT NOT NULL DEFAULT 0,
  `dataHoraInclusao` DATETIME NOT NULL,
  `idUsuarios` BIGINT NOT NULL,
  PRIMARY KEY (`idrotas`),
  INDEX `fk_rotas_usuarios` (`idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_rotas_usuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`erros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`erros` ;

CREATE TABLE IF NOT EXISTS `inventus`.`erros` (
  `iderros` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `log` TEXT NOT NULL,
  `dataHoraCadastro` DATETIME NOT NULL,
  `idrotas` BIGINT NOT NULL,
  PRIMARY KEY (`iderros`),
  INDEX `fk_erros_rotas` (`idrotas` ASC) VISIBLE,
  CONSTRAINT `fk_erros_rotas`
    FOREIGN KEY (`idrotas`)
    REFERENCES `inventus`.`rotas` (`idrotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`clientes` ;

CREATE TABLE IF NOT EXISTS `inventus`.`clientes` (
  `idClientes` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `cnpj` VARCHAR(14) NULL,
  `ehFilial` TINYINT NULL,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_clientes_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_clientes_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_clientes_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_usuarios_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_usuarios_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_usuarios_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `inventus`.`fornecedor` (
  `idFornecedor` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `cnpj` VARCHAR(14) NULL,
  `cpf` VARCHAR(14) NULL,
  `idEnderecos` BIGINT NULL,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `idEnderecos_UNIQUE` (`idEnderecos` ASC) VISIBLE,
  INDEX `fk_fornecedor_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_fornecedor_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_fornecedor_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  CONSTRAINT `fk_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`entradas` ;

CREATE TABLE IF NOT EXISTS `inventus`.`entradas` (
  `idEntradas` BIGINT NOT NULL AUTO_INCREMENT,
  `idFornecedor` BIGINT NOT NULL,
  `idEstoque` BIGINT NOT NULL,
  `quantidadeEntrou` INT NOT NULL,
  `valorUnidade` DECIMAL(10,2) NOT NULL,
  `detalhamento` TEXT NULL,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idEntradas`),
  INDEX `fk_entradas_fornecedor` (`idFornecedor` ASC) VISIBLE,
  INDEX `fk_entradas_estoque` (`idEstoque` ASC) VISIBLE,
  INDEX `fk_entradas_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_entradas_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_entradas_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  CONSTRAINT `fk_entradas_fornecedor`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `inventus`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entradas_estoque`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `inventus`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entradas_usuarios_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entradas_usuarios_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entradas_usuarios_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventus`.`saidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventus`.`saidas` ;

CREATE TABLE IF NOT EXISTS `inventus`.`saidas` (
  `idSaidas` BIGINT NOT NULL AUTO_INCREMENT,
  `idClientes` BIGINT NOT NULL,
  `idEstoque` BIGINT NOT NULL,
  `quantidadeSaiu` INT NOT NULL,
  `valorVendidoUnidade` DECIMAL(10,2) NOT NULL,
  `detalhamento` TEXT NULL,
  `dataHoraInclusao` DATETIME NOT NULL,
  `dataHoraAtualizacao` DATETIME NULL,
  `dataHoraExclusao` DATETIME NULL,
  `idUsuarioInclusao` BIGINT NOT NULL,
  `idUsuarioAlteracao` BIGINT NULL,
  `idUsuarioExclusao` BIGINT NULL,
  PRIMARY KEY (`idSaidas`),
  INDEX `fk_saidas_estoque` (`idEstoque` ASC) VISIBLE,
  INDEX `fk_saidas_usuarios_inclusao` (`idUsuarioInclusao` ASC) VISIBLE,
  INDEX `fk_saidas_usuarios_alteracao` (`idUsuarioAlteracao` ASC) VISIBLE,
  INDEX `fk_saidas_usuarios_exclusao` (`idUsuarioExclusao` ASC) VISIBLE,
  INDEX `fk_saidas_clientes` (`idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_saidas_estoque`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `inventus`.`estoque` (`idestoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saidas_usuarios_inclusao`
    FOREIGN KEY (`idUsuarioInclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saidas_usuarios_alteracao`
    FOREIGN KEY (`idUsuarioAlteracao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saidas_usuarios_exclusao`
    FOREIGN KEY (`idUsuarioExclusao`)
    REFERENCES `inventus`.`usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saidas_clientes`
    FOREIGN KEY (`idClientes`)
    REFERENCES `inventus`.`clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
